set -g  prefix C-s
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded!"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g allow-passthrough on
# look
set -ga update-environment kitty
set -g default-terminal "${TERM}"
set -sg terminal-overrides ",*:RGB"
set -g pane-border-lines simple
set -g repeat-time 1000

# colors
fg="#ebdbb2"          # normal text (fg1)
bg="#1d2021"          # hard backgroun (bg0)

black="#1d2021"       # color0: bg0
red="#cc241d"          # color1
green="#98971a"        # color2
yellow="#d79921"       # color3
blue="#458588"         # color4
magenta="#b16286"      # color5 (purple)
cyan="#689d6a"         # color6 (aqua)
white="#a89984"        # color7: fg4 (light gray)

set -g status-left-length 100
set -g status-style "fg=${fg}, bg=default"
set -g status-right "#[fg=${cyan}] Pane: #P"
set -g status-left "#[fg=${green}, bold]  #S #[fg=${fg}, nobold]| "

set -g window-status-current-format "#[fg=${cyan}]#[underscore]#I:#W"
set -g window-status-format "#I:#W"
set -g message-style "fg=${fg}, bg=default"
bind | split-window -h
bind - split-window -v
bind f resize-pane -Z
set -g allow-passthrough on
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


set -g @plugin 'sainnhe/tmux-fzf'
set-option -g @plugin 'b0o/tmux-autoreload'
set-option -g @tmux-autoreload-configs '/home/arkar/.config/tmux/tmux.conf'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


