# colors
fg="#D3C6AA"          # normal text (fg1)
bg="#272E33"          # hard backgroun (bg0)

black="#272E33"		# color0: bg0
red="#E67E80"          # color1
green="#A7C080"        # color2
yellow="#DBBC7F"       # color3
blue="#7FBBB3"         # color4
magenta="#D699B6"     # color5 (purple)
cyan="#689d6a"         # color6 (aqua)
white="#D3C6AA"        # color7: fg4 (light gray)

set -g status-left-length 100
set -g status-style "fg=${fg}, bg=default"
set -g status-right "#[fg=${cyan}] Pane: #P"
set -g status-left "#[fg=${cyan}, bold]  #S #[fg=${fg}, nobold]| "

set -g window-status-current-format "#[fg=${cyan}]#[underscore]#I:#W"
set -g window-status-format "#I:#W"
set -g message-style "fg=${fg}, bg=default"
