# colors
fg="#ebdbb2"          # normal text (fg1)
bg="#1d2021"          # hard backgroun (bg0)

black="#1d2021"       # color0: bg0
red="#cc241d"          # color1
green="#98971a"        # color2
yellow="#d79921"       # color3
blue="#458588"         # color4
magenta="#b16286"      # color5 (purple)
cyan="#689d6a"         # color6 (aqua)
white="#a89984"        # color7: fg4 (light gray)

set -g status-left-length 100
set -g status-style "fg=${fg}, bg=default"
set -g status-right "#[fg=${cyan}] Pane: #P"
set -g status-left "#[fg=${green}, bold]  #S #[fg=${fg}, nobold]| "

set -g window-status-current-format "#[fg=${cyan}]#[underscore]#I:#W"
set -g window-status-format "#I:#W"
set -g message-style "fg=${fg}, bg=default"
