
background = 0xFF1E1E2E   # base
base = 0xFF181825         # mantle
alternate_base = 0xFF313244  # surface0

text = 0xFFCdd6f4         # text
bright_text = 0xFFFFFFFF

accent = 0xFFcba6f7       # mauve
accent_secondary = 0xFF89b4fa  # blue

font_family = "Caskaydia Cove Nerd Font"
font_family_monospace = "Caskaydia Cove Nerd Font Mono"

rounding_large = 0
rounding_small = 0
