format = """
$os\
$directory\
$git_branch\
$fill\
$lua\
$c\
$haskell\
$line_break\
$character"""
[fill]
symbol = ' '
[directory]
style = "green"
[lua]
symbol = ''
format = '[$symbol ($version) ]($style)'
[c]
symbol = 'ℂ'
format = '[$symbol ($version) ]($style)'
[haskell]
symbol = 'λ'
format = '[$symbol ($version) ]($style)'
[os]
disabled = false
style = "blue"
format = "[$symbol ]($style) "
[os.symbols]
Arch = "☭ "
Artix = " "
[character]
success_symbol = "[λ ](bold)"
error_symbol = "[󱃠 ](red)"
vimcmd_symbol = "[Λ ](green)"
vimcmd_replace_one_symbol = "[Λ ](purple)"
vimcmd_replace_symbol = "[Λ ](purple)"
vimcmd_visual_symbol = "[Λ ](yellow)"
