return {
	"xiyaowong/transparent.nvim",
	event = "ColorScheme",
	opts = {
		extra_groups = {
			"NormalFloat",
			"FloatBorder",
			"FloatTitle",
			"FloatFootnote",
			"LspHoverFloat",
			"LspFloatWinBorder",
			"LspFloatWinNormal",
			"BlinkCmpMenu",
			"BlinkCmpMenuNormal",
			"BlinkCmpMenuNormalNC",
			"BlinkCmpMenuBorder",
			"BlinkCmpMenuSelection",
			"BlinkCmpMenuSelectionNC",
			"BlinkCmpDoc",
			"BlinkCmpDocNormal",
			"BlinkCmpDocNormalNC",
			"BlinkCmpDocBorder",
			"BlinkCmpDocCursorLine",
			"BlinkCmpDocSeparator",
			"BlinkCmpSignatureHelp",
			"BlinkCmpSignatureHelpNormal",
			"BlinkCmpSignatureHelpNormalNC",
			"BlinkCmpSignatureHelpBorder",
			"BlinkCmpSignatureHelpActiveParameter",
			"BlinkCmpGhostText",
			"BlinkCmpLabel",
			"BlinkCmpLabelDetail",
			"BlinkCmpLabelDescription",
			"BlinkCmpLabelMatch",
			"BlinkCmpLabelDeprecated",
			"BlinkCmpKind",
			"BlinkCmpSource",
			"BlinkCmpScrollBarThumb",
			"BlinkCmpScrollBarGutter",
		},
		exclude_groups = {},
	},
}
